name: ntfy

services:
  ntfy:
    image: masgeek/ntfy:latest
    build:
        context: .
        dockerfile: Dockerfile
    container_name: ntfy
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - NTFY_CACHE_FILE=/var/cache/ntfy/cache.db
      - NTFY_AUTH_FILE=/var/lib/ntfy/auth.db
      - NTFY_ATTACHMENT_CACHE_DIR=/var/cache/ntfy/attachments
      - NTFY_ENABLE_LOGIN=true
      - NTFY_ENABLE_SIGNUP=false
      - NTFY_BEHIND_PROXY=false
    volumes:
      - ntfy_cache:/var/cache/ntfy
      - ntfy_data:/var/lib/ntfy
      # - ./server.yml:/etc/ntfy/server.yml:ro
    command:
      - serve
    healthcheck:
      test: ["CMD-SHELL", "wget -q --tries=1 http://localhost:80/v1/health -O - | grep -Eo '\"healthy\"\\s*:\\s*true' || exit 1"]
      interval: 60s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ntfy_network

volumes:
  ntfy_cache:
    driver: local
  ntfy_data:
    driver: local

networks:
  ntfy_network:
    driver: bridge